import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const neueMachina = localFont({
  variable: '--font-neue-machina',
  src: [
    {
      path: './assets/fonts/neuemachina-light.otf',
      weight: '300',
    },
    {
      path: './assets/fonts/neuemachina-regular.otf',
      weight: '400',
    },
    {
      path: './assets/fonts/neuemachina-ultrabold.otf',
      weight: '800',
    },
  ],
});

const nextBook = localFont({
  variable: '--font-next-book',
  src: [
    {
      path: './assets/fonts/next-otf/NEXT-Book-Regular.otf',
      weight: '400',
    },
  ],
});

const nextPoster = localFont({
  variable: '--font-next-poster',
  src: [
    {
      path: './assets/fonts/next-otf/NEXT-Poster-Regular.otf',
      weight: '400',
    },
    {
      path: './assets/fonts/next-otf/NEXT-Poster-Bold.otf',
      weight: '700',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${neueMachina.variable} ${nextBook.variable} ${nextPoster.variable} bg-[#030303]`}
      >
        {children}
      </body>
    </html>
  );
}
